"""Add farmer_id to orders

Revision ID: 122bafeb4ff3
Revises: ba3bf874fa44
Create Date: 2025-05-21 10:39:33.999073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122bafeb4ff3'
down_revision = 'ba3bf874fa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['farmer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
