"""Deleted farmer id to orders

Revision ID: 235a1a13f68f
Revises: 122bafeb4ff3
Create Date: 2025-05-21 10:42:48.517648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235a1a13f68f'
down_revision = '122bafeb4ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_farmer_id_fkey', type_='foreignkey')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_farmer_id_fkey', 'users', ['farmer_id'], ['id'])

    # ### end Alembic commands ###
