"""Add part column to animal

Revision ID: 43a37d001196
Revises: c9b1db8185fd
Create Date: 2025-05-19 17:36:53.375527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a37d001196'
down_revision = 'c9b1db8185fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part', sa.String(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('part')

    # ### end Alembic commands ###
